
###

POST http://{{host}}/v1/capture/start
Content-Type: application/json

{
  "Id": "Daily",
  "Timestamp":1
}

###

POST http://{{host}}/v1/capture/stop
Content-Type: application/json

{
  "Id": "Daily",
  "Timestamp":2
}

