POST http://{{host}}/v1/projects
Content-Type: application/json

{
  "Id": "WEB-12020",
  "Description": "My first project"
}

###
DELETE http://{{host}}/v1/project/WEB-12020
Content-Type: application/json

###
GET http://{{host}}/v1/project/WEB-12020
Content-Type: application/json

###
POST http://{{host}}/v1/captures/start
Content-Type: application/json

{
  "Id": "WEB-12020",
  "Timestamp":24582395
}
###
POST http://{{host}}/v1/captures/stop
Content-Type: application/json

{
  "Id": "WEB-12020",
  "Timestamp":24582395
}

###
GET http://{{host}}/apidocs