POST http://127.0.0.1:8001/v1/projects
Content-Type: application/json

{
  "Id": "WEB-12020",
  "Description": "My first project"
}

###

PUT http://127.0.0.1:8001/v1/projects
Content-Type: application/json

{
  "Id": "WEB-12020",
  "Description": "My first project"
}

###

DELETE http://127.0.0.1:8001/v1/project/WEB-12020
Content-Type: application/json

###


GET http://127.0.0.1:8001/v1/project/WEB-12020
Content-Type: application/json

###