swagger: "2.0"
info:
  description: "Swagger definition for time toggle app in toggleperfect"
  version: "1.0.0"
  title: "Timetoggle API"
host: "toggleperfect"
basePath: "/v1"
tags:
  - name: "project"
    description: "Everything about Projects"
schemes:
  - "http"
paths:
  /projects:
    post:
      tags:
        - "project"
      summary: "Add a new project"
      description: ""
      operationId: "addProject"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Project object that needs to be added to the store"
          required: true
          schema:
            $ref: "#/definitions/Project"
      responses:
        204:
          description: "OK"
        405:
          description: "Invalid input"
    put:
      tags:
        - "project"
      summary: "Update an existing project"
      description: ""
      operationId: "updateProject"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Project object that needs to be added to the store"
          required: true
          schema:
            $ref: "#/definitions/Project"
      responses:
        204:
          description: "OK"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Project not found"
        405:
          description: "Validation exception"
  /project/{projectId}:
    get:
      tags:
        - "project"
      summary: "Find project by ID"
      description: "Returns a single project"
      operationId: "getProjectById"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "projectId"
          in: "path"
          description: "ID of project to return"
          required: true
          type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Project"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Project not found"
    delete:
      tags:
        - "project"
      summary: "Deletes a project"
      description: ""
      operationId: "deleteProject"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "projectId"
          in: "path"
          description: "Project id to delete"
          required: true
          type: "string"
      responses:
        204:
          description: "OK"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Project not found"

definitions:
  Project:
    type: "object"
    required:
      - "id"
      - "description"
    properties:
      id:
        type: "string"
        "x-nullable": false
      description:
        type: "string"
        "x-nullable": false
    xml:
      name: "Project"
